### PR TITLE
secure DOIs

### PR DESCRIPTION
**Pull request by katrinleinweber**
new suggested resolver, see https://www.doi.org/

### CODE REVIEW

**Comment by pfaffman** [comment]
Well, I guess I should jump on the secure bandwagon too! Thanks, @katrinleinweber.

I guess this means that at least one other person is using this code!

**Comment by katrinleinweber** [comment]
You're welcome! I'm not managing a Discourse myself, but I'll suggest your plugin to the admins of the ones I use :-)

**Comment by pfaffman** [comment]
Ha. Oh well. So are you a doi aficionado? I was quite surprised to get a PR
on such an esoteric plugin. How'd you even find it?

**Comment by katrinleinweber** [comment]
_cough_ https://twitter.com/kaleimai/status/716238946414510086

**Comment by pfaffman** [comment]
Hilarious. I thought that it must be a fairly recent change.

Thanks for bringing it to my attention, even if it dashed my hopes that
someone was using my code. I guess this is a reason to put all of my
worthless code online. You could have submitted PRs for my personal emacs
DOI scripts too!

Jay Pfaffman jay@pfaffman.com
865-226-9465

**Comment by katrinleinweber** [comment]
That's too personal :-D

**Pull request merged**
